/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.Test;


/**
 * Model tests for AbstractTrackerItemReference
 */
public class AbstractTrackerItemReferenceTest {
    private final AbstractTrackerItemReference model = new AbstractTrackerItemReference();

    /**
     * Model tests for AbstractTrackerItemReference
     */
    @Test
    public void testAbstractTrackerItemReference() {
        // TODO: test AbstractTrackerItemReference
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'itemRevision'
     */
    @Test
    public void itemRevisionTest() {
        // TODO: test itemRevision
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
