/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.Test;


/**
 * Model tests for AttachmentMigrationRequest
 */
public class AttachmentMigrationRequestTest {
    private final AttachmentMigrationRequest model = new AttachmentMigrationRequest();

    /**
     * Model tests for AttachmentMigrationRequest
     */
    @Test
    public void testAttachmentMigrationRequest() {
        // TODO: test AttachmentMigrationRequest
    }

    /**
     * Test the property 'targetItem'
     */
    @Test
    public void targetItemTest() {
        // TODO: test targetItem
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'createdBy'
     */
    @Test
    public void createdByTest() {
        // TODO: test createdBy
    }

    /**
     * Test the property 'modifiedAt'
     */
    @Test
    public void modifiedAtTest() {
        // TODO: test modifiedAt
    }

    /**
     * Test the property 'modifiedBy'
     */
    @Test
    public void modifiedByTest() {
        // TODO: test modifiedBy
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'descriptionFormat'
     */
    @Test
    public void descriptionFormatTest() {
        // TODO: test descriptionFormat
    }

    /**
     * Test the property 'migrationAction'
     */
    @Test
    public void migrationActionTest() {
        // TODO: test migrationAction
    }

    /**
     * Test the property 'files'
     */
    @Test
    public void filesTest() {
        // TODO: test files
    }

}
