/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for DependencyEntityReferenceAllOf
 */
public class DependencyEntityReferenceAllOfTest {
    private final DependencyEntityReferenceAllOf model = new DependencyEntityReferenceAllOf();

    /**
     * Model tests for DependencyEntityReferenceAllOf
     */
    @Test
    public void testDependencyEntityReferenceAllOf() {
        // TODO: test DependencyEntityReferenceAllOf
    }

    /**
     * Test the property 'typeId'
     */
    @Test
    public void typeIdTest() {
        // TODO: test typeId
    }

}
