/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FastDateFormatLocale
 */
public class FastDateFormatLocaleTest {
    private final FastDateFormatLocale model = new FastDateFormatLocale();

    /**
     * Model tests for FastDateFormatLocale
     */
    @Test
    public void testFastDateFormatLocale() {
        // TODO: test FastDateFormatLocale
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'script'
     */
    @Test
    public void scriptTest() {
        // TODO: test script
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'variant'
     */
    @Test
    public void variantTest() {
        // TODO: test variant
    }

    /**
     * Test the property 'extensionKeys'
     */
    @Test
    public void extensionKeysTest() {
        // TODO: test extensionKeys
    }

    /**
     * Test the property 'unicodeLocaleAttributes'
     */
    @Test
    public void unicodeLocaleAttributesTest() {
        // TODO: test unicodeLocaleAttributes
    }

    /**
     * Test the property 'unicodeLocaleKeys'
     */
    @Test
    public void unicodeLocaleKeysTest() {
        // TODO: test unicodeLocaleKeys
    }

    /**
     * Test the property 'iso3Language'
     */
    @Test
    public void iso3LanguageTest() {
        // TODO: test iso3Language
    }

    /**
     * Test the property 'iso3Country'
     */
    @Test
    public void iso3CountryTest() {
        // TODO: test iso3Country
    }

    /**
     * Test the property 'displayLanguage'
     */
    @Test
    public void displayLanguageTest() {
        // TODO: test displayLanguage
    }

    /**
     * Test the property 'displayScript'
     */
    @Test
    public void displayScriptTest() {
        // TODO: test displayScript
    }

    /**
     * Test the property 'displayCountry'
     */
    @Test
    public void displayCountryTest() {
        // TODO: test displayCountry
    }

    /**
     * Test the property 'displayVariant'
     */
    @Test
    public void displayVariantTest() {
        // TODO: test displayVariant
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

}
