/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InternalServerErrorException
 */
public class InternalServerErrorExceptionTest {
    private final InternalServerErrorException model = new InternalServerErrorException();

    /**
     * Model tests for InternalServerErrorException
     */
    @Test
    public void testInternalServerErrorException() {
        // TODO: test InternalServerErrorException
    }

    /**
     * Test the property 'resourceUri'
     */
    @Test
    public void resourceUriTest() {
        // TODO: test resourceUri
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
