/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.Test;


/**
 * Model tests for OptionChoiceField
 */
public class OptionChoiceFieldTest {
    private final OptionChoiceField model = new OptionChoiceField();

    /**
     * Model tests for OptionChoiceField
     */
    @Test
    public void testOptionChoiceField() {
        // TODO: test OptionChoiceField
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'hidden'
     */
    @Test
    public void hiddenTest() {
        // TODO: test hidden
    }

    /**
     * Test the property 'valueModel'
     */
    @Test
    public void valueModelTest() {
        // TODO: test valueModel
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'legacyRestName'
     */
    @Test
    public void legacyRestNameTest() {
        // TODO: test legacyRestName
    }

    /**
     * Test the property 'trackerItemField'
     */
    @Test
    public void trackerItemFieldTest() {
        // TODO: test trackerItemField
    }

    /**
     * Test the property 'mandatoryInStatuses'
     */
    @Test
    public void mandatoryInStatusesTest() {
        // TODO: test mandatoryInStatuses
    }

    /**
     * Test the property 'formula'
     */
    @Test
    public void formulaTest() {
        // TODO: test formula
    }

    /**
     * Test the property 'hideIfDependencyFormula'
     */
    @Test
    public void hideIfDependencyFormulaTest() {
        // TODO: test hideIfDependencyFormula
    }

    /**
     * Test the property 'mandatoryIfDependencyFormula'
     */
    @Test
    public void mandatoryIfDependencyFormulaTest() {
        // TODO: test mandatoryIfDependencyFormula
    }

    /**
     * Test the property 'multipleValues'
     */
    @Test
    public void multipleValuesTest() {
        // TODO: test multipleValues
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'referenceType'
     */
    @Test
    public void referenceTypeTest() {
        // TODO: test referenceType
    }

}
