/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReferredTestStepFieldValueAllOf
 */
public class ReferredTestStepFieldValueAllOfTest {
    private final ReferredTestStepFieldValueAllOf model = new ReferredTestStepFieldValueAllOf();

    /**
     * Model tests for ReferredTestStepFieldValueAllOf
     */
    @Test
    public void testReferredTestStepFieldValueAllOf() {
        // TODO: test ReferredTestStepFieldValueAllOf
    }

    /**
     * Test the property 'referredStepId'
     */
    @Test
    public void referredStepIdTest() {
        // TODO: test referredStepId
    }

    /**
     * Test the property 'referredTestCaseId'
     */
    @Test
    public void referredTestCaseIdTest() {
        // TODO: test referredTestCaseId
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
