/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportReferencedRowAllOf
 */
public class ReportReferencedRowAllOfTest {
    private final ReportReferencedRowAllOf model = new ReportReferencedRowAllOf();

    /**
     * Model tests for ReportReferencedRowAllOf
     */
    @Test
    public void testReportReferencedRowAllOf() {
        // TODO: test ReportReferencedRowAllOf
    }

    /**
     * Test the property 'cells'
     */
    @Test
    public void cellsTest() {
        // TODO: test cells
    }

    /**
     * Test the property 'isRealResult'
     */
    @Test
    public void isRealResultTest() {
        // TODO: test isRealResult
    }

    /**
     * Test the property 'itemRef'
     */
    @Test
    public void itemRefTest() {
        // TODO: test itemRef
    }

    /**
     * Test the property 'outlineLevel'
     */
    @Test
    public void outlineLevelTest() {
        // TODO: test outlineLevel
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

}
