/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.model.TrackerItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ReportItem
 */
public class ReportItemTest {
    private final ReportItem model = new ReportItem();

    /**
     * Model tests for ReportItem
     */
    @Test
    public void testReportItem() {
        // TODO: test ReportItem
    }

    /**
     * Test the property 'item'
     */
    @Test
    public void itemTest() {
        // TODO: test item
    }

    /**
     * Test the property 'outlineLevel'
     */
    @Test
    public void outlineLevelTest() {
        // TODO: test outlineLevel
    }

    /**
     * Test the property 'isRealResult'
     */
    @Test
    public void isRealResultTest() {
        // TODO: test isRealResult
    }

}
