/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.Test;


/**
 * Model tests for TooManyRequestsException
 */
public class TooManyRequestsExceptionTest {
    private final TooManyRequestsException model = new TooManyRequestsException();

    /**
     * Model tests for TooManyRequestsException
     */
    @Test
    public void testTooManyRequestsException() {
        // TODO: test TooManyRequestsException
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'resourceUri'
     */
    @Test
    public void resourceUriTest() {
        // TODO: test resourceUri
    }

    /**
     * Test the property 'retryAfterSecond'
     */
    @Test
    public void retryAfterSecondTest() {
        // TODO: test retryAfterSecond
    }

}
