/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for TrackerItemSearchRequest
 */
public class TrackerItemSearchRequestTest {
    private final TrackerItemSearchRequest model = new TrackerItemSearchRequest();

    /**
     * Model tests for TrackerItemSearchRequest
     */
    @Test
    public void testTrackerItemSearchRequest() {
        // TODO: test TrackerItemSearchRequest
    }

    /**
     * Test the property 'baselineId'
     */
    @Test
    public void baselineIdTest() {
        // TODO: test baselineId
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'queryString'
     */
    @Test
    public void queryStringTest() {
        // TODO: test queryString
    }

}
