/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.model.AbstractFieldValue;
import com.intland.swagger.client.model.TableFieldValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateTrackerItemField
 */
public class UpdateTrackerItemFieldTest {
    private final UpdateTrackerItemField model = new UpdateTrackerItemField();

    /**
     * Model tests for UpdateTrackerItemField
     */
    @Test
    public void testUpdateTrackerItemField() {
        // TODO: test UpdateTrackerItemField
    }

    /**
     * Test the property 'fieldValues'
     */
    @Test
    public void fieldValuesTest() {
        // TODO: test fieldValues
    }

    /**
     * Test the property 'tableValues'
     */
    @Test
    public void tableValuesTest() {
        // TODO: test tableValues
    }

}
