/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateWorkingSet500Response
 */
public class UpdateWorkingSet500ResponseTest {
    private final UpdateWorkingSet500Response model = new UpdateWorkingSet500Response();

    /**
     * Model tests for UpdateWorkingSet500Response
     */
    @Test
    public void testUpdateWorkingSet500Response() {
        // TODO: test UpdateWorkingSet500Response
    }

    /**
     * Test the property 'cause'
     */
    @Test
    public void causeTest() {
        // TODO: test cause
    }

    /**
     * Test the property 'detail'
     */
    @Test
    public void detailTest() {
        // TODO: test detail
    }

    /**
     * Test the property 'localizedMessage'
     */
    @Test
    public void localizedMessageTest() {
        // TODO: test localizedMessage
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'stackTrace'
     */
    @Test
    public void stackTraceTest() {
        // TODO: test stackTrace
    }

    /**
     * Test the property 'suppressed'
     */
    @Test
    public void suppressedTest() {
        // TODO: test suppressed
    }

}
