/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.model.AbstractTrackerItemReference;
import com.intland.swagger.client.model.TrackerItemRevision;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpstreamTrackerItemReference
 */
public class UpstreamTrackerItemReferenceTest {
    private final UpstreamTrackerItemReference model = new UpstreamTrackerItemReference();

    /**
     * Model tests for UpstreamTrackerItemReference
     */
    @Test
    public void testUpstreamTrackerItemReference() {
        // TODO: test UpstreamTrackerItemReference
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'itemRevision'
     */
    @Test
    public void itemRevisionTest() {
        // TODO: test itemRevision
    }

}
