/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for WikiTextFieldValue
 */
public class WikiTextFieldValueTest {
    private final WikiTextFieldValue model = new WikiTextFieldValue();

    /**
     * Model tests for WikiTextFieldValue
     */
    @Test
    public void testWikiTextFieldValue() {
        // TODO: test WikiTextFieldValue
    }

    /**
     * Test the property 'fieldId'
     */
    @Test
    public void fieldIdTest() {
        // TODO: test fieldId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sharedFieldName'
     */
    @Test
    public void sharedFieldNameTest() {
        // TODO: test sharedFieldName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
