/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * FieldReferenceAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-13T13:40:39.450514+01:00[Europe/Budapest]")
public class FieldReferenceAllOf {
  public static final String SERIALIZED_NAME_TRACKER_ID = "trackerId";
  @SerializedName(SERIALIZED_NAME_TRACKER_ID)
  private Integer trackerId;


  public FieldReferenceAllOf trackerId(Integer trackerId) {
    
    this.trackerId = trackerId;
    return this;
  }

   /**
   * Id of the tracker
   * @return trackerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1000", value = "Id of the tracker")

  public Integer getTrackerId() {
    return trackerId;
  }


  public void setTrackerId(Integer trackerId) {
    this.trackerId = trackerId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FieldReferenceAllOf fieldReferenceAllOf = (FieldReferenceAllOf) o;
    return Objects.equals(this.trackerId, fieldReferenceAllOf.trackerId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(trackerId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FieldReferenceAllOf {\n");
    sb.append("    trackerId: ").append(toIndentedString(trackerId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

