/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.io.IOException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.JSON;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Basic properties of maintenance mode
 */
@ApiModel(description = "Basic properties of maintenance mode")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-18T11:38:56.646+02:00[Europe/Budapest]")
public class MaintenanceMode {
  public static final String SERIALIZED_NAME_PROPERTIES = "properties";
  @SerializedName(SERIALIZED_NAME_PROPERTIES)
  private MaintenanceModeProperties properties;

  /**
   * System mode
   */
  @JsonAdapter(SystemModeEnum.Adapter.class)
  public enum SystemModeEnum {
    NORMAL("NORMAL"),
    
    MAINTENANCE("MAINTENANCE");

    private String value;

    SystemModeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SystemModeEnum fromValue(String value) {
      for (SystemModeEnum b : SystemModeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<SystemModeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SystemModeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SystemModeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return SystemModeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SYSTEM_MODE = "systemMode";
  @SerializedName(SERIALIZED_NAME_SYSTEM_MODE)
  private SystemModeEnum systemMode;

  public MaintenanceMode() { 
  }

  public MaintenanceMode properties(MaintenanceModeProperties properties) {
    
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public MaintenanceModeProperties getProperties() {
    return properties;
  }


  public void setProperties(MaintenanceModeProperties properties) {
    this.properties = properties;
  }


  public MaintenanceMode systemMode(SystemModeEnum systemMode) {
    
    this.systemMode = systemMode;
    return this;
  }

   /**
   * System mode
   * @return systemMode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "System mode")

  public SystemModeEnum getSystemMode() {
    return systemMode;
  }


  public void setSystemMode(SystemModeEnum systemMode) {
    this.systemMode = systemMode;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MaintenanceMode maintenanceMode = (MaintenanceMode) o;
    return Objects.equals(this.properties, maintenanceMode.properties) &&
        Objects.equals(this.systemMode, maintenanceMode.systemMode);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(properties, systemMode);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MaintenanceMode {\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    systemMode: ").append(toIndentedString(systemMode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("properties");
    openapiFields.add("systemMode");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MaintenanceMode
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MaintenanceMode.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MaintenanceMode is not found in the empty JSON string", MaintenanceMode.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MaintenanceMode.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MaintenanceMode` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `properties`
      if (jsonObj.getAsJsonObject("properties") != null) {
        MaintenanceModeProperties.validateJsonObject(jsonObj.getAsJsonObject("properties"));
      }
      if (jsonObj.get("systemMode") != null && !jsonObj.get("systemMode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `systemMode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("systemMode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MaintenanceMode.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MaintenanceMode' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MaintenanceMode> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MaintenanceMode.class));

       return (TypeAdapter<T>) new TypeAdapter<MaintenanceMode>() {
           @Override
           public void write(JsonWriter out, MaintenanceMode value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MaintenanceMode read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MaintenanceMode given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MaintenanceMode
  * @throws IOException if the JSON string is invalid with respect to MaintenanceMode
  */
  public static MaintenanceMode fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MaintenanceMode.class);
  }

 /**
  * Convert an instance of MaintenanceMode to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

