/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.JSON;

import io.swagger.annotations.ApiModelProperty;

/**
 * MemberFieldAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-18T17:30:04.683+02:00[Europe/Budapest]")
public class MemberFieldAllOf {
  /**
   * Supported member type of a member field
   */
  @JsonAdapter(MemberTypesEnum.Adapter.class)
  public enum MemberTypesEnum {
    USER("USER"),
    
    ROLE("ROLE"),
    
    GROUP("GROUP");

    private String value;

    MemberTypesEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MemberTypesEnum fromValue(String value) {
      for (MemberTypesEnum b : MemberTypesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<MemberTypesEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MemberTypesEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MemberTypesEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return MemberTypesEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_MEMBER_TYPES = "memberTypes";
  @SerializedName(SERIALIZED_NAME_MEMBER_TYPES)
  private List<MemberTypesEnum> memberTypes = null;

  public static final String SERIALIZED_NAME_MULTIPLE_VALUES = "multipleValues";
  @SerializedName(SERIALIZED_NAME_MULTIPLE_VALUES)
  private Boolean multipleValues;

  public MemberFieldAllOf() { 
  }

  public MemberFieldAllOf memberTypes(List<MemberTypesEnum> memberTypes) {
    
    this.memberTypes = memberTypes;
    return this;
  }

  public MemberFieldAllOf addMemberTypesItem(MemberTypesEnum memberTypesItem) {
    if (this.memberTypes == null) {
      this.memberTypes = new ArrayList<>();
    }
    this.memberTypes.add(memberTypesItem);
    return this;
  }

   /**
   * Supported member type of a member field
   * @return memberTypes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Supported member type of a member field")

  public List<MemberTypesEnum> getMemberTypes() {
    return memberTypes;
  }


  public void setMemberTypes(List<MemberTypesEnum> memberTypes) {
    this.memberTypes = memberTypes;
  }


  public MemberFieldAllOf multipleValues(Boolean multipleValues) {
    
    this.multipleValues = multipleValues;
    return this;
  }

   /**
   * Multiple values state of a field
   * @return multipleValues
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Multiple values state of a field")

  public Boolean getMultipleValues() {
    return multipleValues;
  }


  public void setMultipleValues(Boolean multipleValues) {
    this.multipleValues = multipleValues;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MemberFieldAllOf memberFieldAllOf = (MemberFieldAllOf) o;
    return Objects.equals(this.memberTypes, memberFieldAllOf.memberTypes) &&
        Objects.equals(this.multipleValues, memberFieldAllOf.multipleValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberTypes, multipleValues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MemberFieldAllOf {\n");
    sb.append("    memberTypes: ").append(toIndentedString(memberTypes)).append("\n");
    sb.append("    multipleValues: ").append(toIndentedString(multipleValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("memberTypes");
    openapiFields.add("multipleValues");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MemberFieldAllOf
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MemberFieldAllOf.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MemberFieldAllOf is not found in the empty JSON string", MemberFieldAllOf.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MemberFieldAllOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MemberFieldAllOf` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // ensure the json data is an array
      if (jsonObj.get("memberTypes") != null && !jsonObj.get("memberTypes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `memberTypes` to be an array in the JSON string but got `%s`", jsonObj.get("memberTypes").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MemberFieldAllOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MemberFieldAllOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MemberFieldAllOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MemberFieldAllOf.class));

       return (TypeAdapter<T>) new TypeAdapter<MemberFieldAllOf>() {
           @Override
           public void write(JsonWriter out, MemberFieldAllOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MemberFieldAllOf read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MemberFieldAllOf given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MemberFieldAllOf
  * @throws IOException if the JSON string is invalid with respect to MemberFieldAllOf
  */
  public static MemberFieldAllOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MemberFieldAllOf.class);
  }

 /**
  * Convert an instance of MemberFieldAllOf to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

