/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.io.IOException;
import java.util.Objects;

import org.joda.time.DateTime;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A tracker item review instance including its reviewers and their decisions
 */
@ApiModel(description = "A tracker item review instance including its reviewers and their decisions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-13T13:40:39.450514+01:00[Europe/Budapest]")
public class TrackerItemReviewVote {
  public static final String SERIALIZED_NAME_USER = "user";
  @SerializedName(SERIALIZED_NAME_USER)
  private UserReference user;

  public static final String SERIALIZED_NAME_AS_ROLE = "asRole";
  @SerializedName(SERIALIZED_NAME_AS_ROLE)
  private RoleReference asRole;

  /**
   * The result of this particular vote
   */
  @JsonAdapter(DecisionEnum.Adapter.class)
  public enum DecisionEnum {
    APPROVED("APPROVED"),
    
    REJECTED("REJECTED"),
    
    UNDECIDED("UNDECIDED");

    private String value;

    DecisionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DecisionEnum fromValue(String value) {
      for (DecisionEnum b : DecisionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DecisionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DecisionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DecisionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DecisionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DECISION = "decision";
  @SerializedName(SERIALIZED_NAME_DECISION)
  private DecisionEnum decision;

  public static final String SERIALIZED_NAME_REVIEWED_AT = "reviewedAt";
  @SerializedName(SERIALIZED_NAME_REVIEWED_AT)
  private DateTime reviewedAt;


  public TrackerItemReviewVote user(UserReference user) {
    
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserReference getUser() {
    return user;
  }


  public void setUser(UserReference user) {
    this.user = user;
  }


  public TrackerItemReviewVote asRole(RoleReference asRole) {
    
    this.asRole = asRole;
    return this;
  }

   /**
   * Get asRole
   * @return asRole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RoleReference getAsRole() {
    return asRole;
  }


  public void setAsRole(RoleReference asRole) {
    this.asRole = asRole;
  }


  public TrackerItemReviewVote decision(DecisionEnum decision) {
    
    this.decision = decision;
    return this;
  }

   /**
   * The result of this particular vote
   * @return decision
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The result of this particular vote")

  public DecisionEnum getDecision() {
    return decision;
  }


  public void setDecision(DecisionEnum decision) {
    this.decision = decision;
  }


  public TrackerItemReviewVote reviewedAt(DateTime reviewedAt) {
    
    this.reviewedAt = reviewedAt;
    return this;
  }

   /**
   * Date and time of the vote
   * @return reviewedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Date and time of the vote")

  public DateTime getReviewedAt() {
    return reviewedAt;
  }


  public void setReviewedAt(DateTime reviewedAt) {
    this.reviewedAt = reviewedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackerItemReviewVote trackerItemReviewVote = (TrackerItemReviewVote) o;
    return Objects.equals(this.user, trackerItemReviewVote.user) &&
        Objects.equals(this.asRole, trackerItemReviewVote.asRole) &&
        Objects.equals(this.decision, trackerItemReviewVote.decision) &&
        Objects.equals(this.reviewedAt, trackerItemReviewVote.reviewedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(user, asRole, decision, reviewedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackerItemReviewVote {\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    asRole: ").append(toIndentedString(asRole)).append("\n");
    sb.append("    decision: ").append(toIndentedString(decision)).append("\n");
    sb.append("    reviewedAt: ").append(toIndentedString(reviewedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

