/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.JSON;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A tracker item review instance including its reviewers and their decisions
 */
@ApiModel(description = "A tracker item review instance including its reviewers and their decisions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-18T17:30:04.683+02:00[Europe/Budapest]")
public class TrackerItemReviewExport {
  public static final String SERIALIZED_NAME_REVIEWERS = "reviewers";
  @SerializedName(SERIALIZED_NAME_REVIEWERS)
  private List<TrackerItemReviewVoteExport> reviewers = null;

  public static final String SERIALIZED_NAME_TRACKER_ITEM_VERSION = "trackerItemVersion";
  @SerializedName(SERIALIZED_NAME_TRACKER_ITEM_VERSION)
  private Integer trackerItemVersion;

  public TrackerItemReviewExport() { 
  }

  public TrackerItemReviewExport reviewers(List<TrackerItemReviewVoteExport> reviewers) {
    
    this.reviewers = reviewers;
    return this;
  }

  public TrackerItemReviewExport addReviewersItem(TrackerItemReviewVoteExport reviewersItem) {
    if (this.reviewers == null) {
      this.reviewers = new ArrayList<>();
    }
    this.reviewers.add(reviewersItem);
    return this;
  }

   /**
   * List of reviewers and their votes
   * @return reviewers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "List of reviewers and their votes")

  public List<TrackerItemReviewVoteExport> getReviewers() {
    return reviewers;
  }


  public void setReviewers(List<TrackerItemReviewVoteExport> reviewers) {
    this.reviewers = reviewers;
  }


  public TrackerItemReviewExport trackerItemVersion(Integer trackerItemVersion) {
    
    this.trackerItemVersion = trackerItemVersion;
    return this;
  }

   /**
   * Version of the Tracker Item at the time of the review
   * @return trackerItemVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Version of the Tracker Item at the time of the review")

  public Integer getTrackerItemVersion() {
    return trackerItemVersion;
  }


  public void setTrackerItemVersion(Integer trackerItemVersion) {
    this.trackerItemVersion = trackerItemVersion;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TrackerItemReviewExport trackerItemReviewExport = (TrackerItemReviewExport) o;
    return Objects.equals(this.reviewers, trackerItemReviewExport.reviewers) &&
        Objects.equals(this.trackerItemVersion, trackerItemReviewExport.trackerItemVersion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reviewers, trackerItemVersion);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TrackerItemReviewExport {\n");
    sb.append("    reviewers: ").append(toIndentedString(reviewers)).append("\n");
    sb.append("    trackerItemVersion: ").append(toIndentedString(trackerItemVersion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("reviewers");
    openapiFields.add("trackerItemVersion");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TrackerItemReviewExport
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (TrackerItemReviewExport.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in TrackerItemReviewExport is not found in the empty JSON string", TrackerItemReviewExport.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TrackerItemReviewExport.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TrackerItemReviewExport` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayreviewers = jsonObj.getAsJsonArray("reviewers");
      if (jsonArrayreviewers != null) {
        // ensure the json data is an array
        if (!jsonObj.get("reviewers").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `reviewers` to be an array in the JSON string but got `%s`", jsonObj.get("reviewers").toString()));
        }

        // validate the optional field `reviewers` (array)
        for (int i = 0; i < jsonArrayreviewers.size(); i++) {
          TrackerItemReviewVoteExport.validateJsonObject(jsonArrayreviewers.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TrackerItemReviewExport.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TrackerItemReviewExport' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TrackerItemReviewExport> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TrackerItemReviewExport.class));

       return (TypeAdapter<T>) new TypeAdapter<TrackerItemReviewExport>() {
           @Override
           public void write(JsonWriter out, TrackerItemReviewExport value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TrackerItemReviewExport read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TrackerItemReviewExport given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TrackerItemReviewExport
  * @throws IOException if the JSON string is invalid with respect to TrackerItemReviewExport
  */
  public static TrackerItemReviewExport fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TrackerItemReviewExport.class);
  }

 /**
  * Convert an instance of TrackerItemReviewExport to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

