/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.model;

import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.intland.swagger.client.JSON;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Wiki page details
 */
@ApiModel(description = "Wiki page details")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-18T17:30:04.683+02:00[Europe/Budapest]")
public class WikiPage {
  public static final String SERIALIZED_NAME_CHANGE_COMMENT = "changeComment";
  @SerializedName(SERIALIZED_NAME_CHANGE_COMMENT)
  private String changeComment;

  public static final String SERIALIZED_NAME_CHILD_PAGES = "childPages";
  @SerializedName(SERIALIZED_NAME_CHILD_PAGES)
  private List<WikiPageReference> childPages = null;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private List<AttachmentReference> comments = null;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private UserReference createdBy;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  /**
   * Description format of the entity
   */
  @JsonAdapter(DescriptionFormatEnum.Adapter.class)
  public enum DescriptionFormatEnum {
    PLAINTEXT("PlainText"),
    
    HTML("Html"),
    
    WIKI("Wiki");

    private String value;

    DescriptionFormatEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DescriptionFormatEnum fromValue(String value) {
      for (DescriptionFormatEnum b : DescriptionFormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DescriptionFormatEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DescriptionFormatEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DescriptionFormatEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DescriptionFormatEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_DESCRIPTION_FORMAT = "descriptionFormat";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION_FORMAT)
  private DescriptionFormatEnum descriptionFormat;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_MARKUP = "markup";
  @SerializedName(SERIALIZED_NAME_MARKUP)
  private String markup;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private UserReference modifiedBy;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PARENT = "parent";
  @SerializedName(SERIALIZED_NAME_PARENT)
  private AbstractReference parent;

  public static final String SERIALIZED_NAME_PROJECT = "project";
  @SerializedName(SERIALIZED_NAME_PROJECT)
  private ProjectReference project;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Integer version;

  public WikiPage() { 
  }

  
  public WikiPage(
     List<WikiPageReference> childPages
  ) {
    this();
    this.childPages = childPages;
  }

  public WikiPage changeComment(String changeComment) {
    
    this.changeComment = changeComment;
    return this;
  }

   /**
   * Summary of the changes in this wiki page version
   * @return changeComment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Summary of the changes in this wiki page version")

  public String getChangeComment() {
    return changeComment;
  }


  public void setChangeComment(String changeComment) {
    this.changeComment = changeComment;
  }


   /**
   * Child pages of the current Wiki page
   * @return childPages
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Child pages of the current Wiki page")

  public List<WikiPageReference> getChildPages() {
    return childPages;
  }




  public WikiPage comments(List<AttachmentReference> comments) {
    
    this.comments = comments;
    return this;
  }

  public WikiPage addCommentsItem(AttachmentReference commentsItem) {
    if (this.comments == null) {
      this.comments = new ArrayList<>();
    }
    this.comments.add(commentsItem);
    return this;
  }

   /**
   * Comments/attachments associated with the wiki page
   * @return comments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Comments/attachments associated with the wiki page")

  public List<AttachmentReference> getComments() {
    return comments;
  }


  public void setComments(List<AttachmentReference> comments) {
    this.comments = comments;
  }


  public WikiPage createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * The date when the entity was created
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the entity was created")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WikiPage createdBy(UserReference createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserReference getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(UserReference createdBy) {
    this.createdBy = createdBy;
  }


  public WikiPage description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Description of the entity
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the entity")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public WikiPage descriptionFormat(DescriptionFormatEnum descriptionFormat) {
    
    this.descriptionFormat = descriptionFormat;
    return this;
  }

   /**
   * Description format of the entity
   * @return descriptionFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description format of the entity")

  public DescriptionFormatEnum getDescriptionFormat() {
    return descriptionFormat;
  }


  public void setDescriptionFormat(DescriptionFormatEnum descriptionFormat) {
    this.descriptionFormat = descriptionFormat;
  }


  public WikiPage id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Id of the entity
   * minimum: 0
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Id of the entity")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public WikiPage markup(String markup) {
    
    this.markup = markup;
    return this;
  }

   /**
   * Content markup of the wiki page
   * @return markup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Content markup of the wiki page")

  public String getMarkup() {
    return markup;
  }


  public void setMarkup(String markup) {
    this.markup = markup;
  }


  public WikiPage modifiedAt(OffsetDateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * The date when the entity was modified
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date when the entity was modified")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public WikiPage modifiedBy(UserReference modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserReference getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(UserReference modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public WikiPage name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name of the entity
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the entity")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public WikiPage parent(AbstractReference parent) {
    
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public AbstractReference getParent() {
    return parent;
  }


  public void setParent(AbstractReference parent) {
    this.parent = parent;
  }


  public WikiPage project(ProjectReference project) {
    
    this.project = project;
    return this;
  }

   /**
   * Get project
   * @return project
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProjectReference getProject() {
    return project;
  }


  public void setProject(ProjectReference project) {
    this.project = project;
  }


  public WikiPage version(Integer version) {
    
    this.version = version;
    return this;
  }

   /**
   * Version of the wiki page
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Version of the wiki page")

  public Integer getVersion() {
    return version;
  }


  public void setVersion(Integer version) {
    this.version = version;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WikiPage wikiPage = (WikiPage) o;
    return Objects.equals(this.changeComment, wikiPage.changeComment) &&
        Objects.equals(this.childPages, wikiPage.childPages) &&
        Objects.equals(this.comments, wikiPage.comments) &&
        Objects.equals(this.createdAt, wikiPage.createdAt) &&
        Objects.equals(this.createdBy, wikiPage.createdBy) &&
        Objects.equals(this.description, wikiPage.description) &&
        Objects.equals(this.descriptionFormat, wikiPage.descriptionFormat) &&
        Objects.equals(this.id, wikiPage.id) &&
        Objects.equals(this.markup, wikiPage.markup) &&
        Objects.equals(this.modifiedAt, wikiPage.modifiedAt) &&
        Objects.equals(this.modifiedBy, wikiPage.modifiedBy) &&
        Objects.equals(this.name, wikiPage.name) &&
        Objects.equals(this.parent, wikiPage.parent) &&
        Objects.equals(this.project, wikiPage.project) &&
        Objects.equals(this.version, wikiPage.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeComment, childPages, comments, createdAt, createdBy, description, descriptionFormat, id, markup, modifiedAt, modifiedBy, name, parent, project, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WikiPage {\n");
    sb.append("    changeComment: ").append(toIndentedString(changeComment)).append("\n");
    sb.append("    childPages: ").append(toIndentedString(childPages)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    descriptionFormat: ").append(toIndentedString(descriptionFormat)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    markup: ").append(toIndentedString(markup)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("changeComment");
    openapiFields.add("childPages");
    openapiFields.add("comments");
    openapiFields.add("createdAt");
    openapiFields.add("createdBy");
    openapiFields.add("description");
    openapiFields.add("descriptionFormat");
    openapiFields.add("id");
    openapiFields.add("markup");
    openapiFields.add("modifiedAt");
    openapiFields.add("modifiedBy");
    openapiFields.add("name");
    openapiFields.add("parent");
    openapiFields.add("project");
    openapiFields.add("version");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WikiPage
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (WikiPage.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in WikiPage is not found in the empty JSON string", WikiPage.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!WikiPage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WikiPage` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("changeComment") != null && !jsonObj.get("changeComment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `changeComment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("changeComment").toString()));
      }
      JsonArray jsonArraychildPages = jsonObj.getAsJsonArray("childPages");
      if (jsonArraychildPages != null) {
        // ensure the json data is an array
        if (!jsonObj.get("childPages").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `childPages` to be an array in the JSON string but got `%s`", jsonObj.get("childPages").toString()));
        }

        // validate the optional field `childPages` (array)
        for (int i = 0; i < jsonArraychildPages.size(); i++) {
          WikiPageReference.validateJsonObject(jsonArraychildPages.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArraycomments = jsonObj.getAsJsonArray("comments");
      if (jsonArraycomments != null) {
        // ensure the json data is an array
        if (!jsonObj.get("comments").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `comments` to be an array in the JSON string but got `%s`", jsonObj.get("comments").toString()));
        }

        // validate the optional field `comments` (array)
        for (int i = 0; i < jsonArraycomments.size(); i++) {
          AttachmentReference.validateJsonObject(jsonArraycomments.get(i).getAsJsonObject());
        };
      }
      // validate the optional field `createdBy`
      if (jsonObj.getAsJsonObject("createdBy") != null) {
        UserReference.validateJsonObject(jsonObj.getAsJsonObject("createdBy"));
      }
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if (jsonObj.get("descriptionFormat") != null && !jsonObj.get("descriptionFormat").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `descriptionFormat` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descriptionFormat").toString()));
      }
      if (jsonObj.get("markup") != null && !jsonObj.get("markup").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `markup` to be a primitive type in the JSON string but got `%s`", jsonObj.get("markup").toString()));
      }
      // validate the optional field `modifiedBy`
      if (jsonObj.getAsJsonObject("modifiedBy") != null) {
        UserReference.validateJsonObject(jsonObj.getAsJsonObject("modifiedBy"));
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `parent`
      if (jsonObj.getAsJsonObject("parent") != null) {
        AbstractReference.validateJsonObject(jsonObj.getAsJsonObject("parent"));
      }
      // validate the optional field `project`
      if (jsonObj.getAsJsonObject("project") != null) {
        ProjectReference.validateJsonObject(jsonObj.getAsJsonObject("project"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WikiPage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WikiPage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WikiPage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WikiPage.class));

       return (TypeAdapter<T>) new TypeAdapter<WikiPage>() {
           @Override
           public void write(JsonWriter out, WikiPage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WikiPage read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WikiPage given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WikiPage
  * @throws IOException if the JSON string is invalid with respect to WikiPage
  */
  public static WikiPage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WikiPage.class);
  }

 /**
  * Convert an instance of WikiPage to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

