/*
 * codebeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.api;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import com.intland.swagger.client.ApiException;
import com.intland.swagger.client.model.Baseline;
import com.intland.swagger.client.model.CreateBaselineRequest;

/**
 * API tests for BaselineApi
 */
@Disabled
public class BaselineApiTest {

    private final BaselineApi api = new BaselineApi();

    /**
     * Create a project or tracker baseline
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createBaselineTest() throws ApiException {
        CreateBaselineRequest createBaselineRequest = null;
        Baseline response = api.createBaseline(createBaselineRequest);
        // TODO: test validations
    }

}
