/*
 * codeBeamer swagger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.intland.swagger.client.api;

import com.intland.swagger.client.ApiException;
import com.intland.swagger.client.model.InlineObject1;
import com.intland.swagger.client.model.TrackerItemRelationsResult;
import com.intland.swagger.client.model.UserDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BaselineApi
 */
@Ignore
public class BaselineApiTest {

    private final BaselineApi api = new BaselineApi();

    
    /**
     * Get tracker items for a baseline version
     *
     * API can be used for fetching basic information of tracker items at a specific baseline version
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBaselineTrackerItemRelationsTest() throws ApiException {
        UserDto user = null;
        Integer itemId = null;
        Integer baselineId = null;
        TrackerItemRelationsResult response = api.getBaselineTrackerItemRelations(user, itemId, baselineId);

        // TODO: test validations
    }
    
    /**
     * Get tracker items for a baseline version
     *
     * API can be used for fetching basic information of tracker items at a specific baseline version
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBaselineTrackerItemsRelationsTest() throws ApiException {
        Integer baselineId = null;
        InlineObject1 inlineObject1 = null;
        List<TrackerItemRelationsResult> response = api.getBaselineTrackerItemsRelations(baselineId, inlineObject1);

        // TODO: test validations
    }
    
}
